version: "3.7"
services:
  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file: .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - database