version: "3.7"
services:
  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: ije_db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USER: postgres
      DB_PASSWORD: $DB_PASSWORD
      DB_URL: $DB_URL
      JWT_SIGNING_KEY: $JWT_SIGNING_KEY